---
- hosts: server
  become: yes
  tasks:
    
    - name: test connection
      ping:
      register: message

    
    - name: print debug message
      debug:
        msg: "{{ message }}"
    
    - name: create directory
      file:
        path: /tmp/rpi
        state: directory
        mode: 0777

    
    - copy:
        src: "{{file_path}}"
        dest: /tmp/rpi/
        mode: 0777
    
    - command: pip3 install RPi.GPIO
    
    # - command: python3 /home/user/rpi/blink_new.py
    #   register: string
    #   ignore_errors: yes
    
    # - name: check
    #   debug:
    #     msg: "{{string}}"

    # - command: python3 /home/user/rpi/blink_old.py
    #   when: string.rc==1